import './layout.module.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <nav className='text-center space-x-8 border-b-2 border-black p-2 '>
          <Link href='/'>메인</Link>
          <Link href='/traval'>여행</Link>
        </nav>

        {children}

      </body>
    </html>
  )
}
